language: node_js

node_js:
- '0.10'

install:
- npm install
- npm install -g codeclimate-test-reporter

after_script:
- cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: 089a3609b0b165e0129ed1e22e8124dea8206700dabebf386d4099a9c3b1b1ae
